version: '3.4'
services:
  restapi:
    image: restapi
    networks:
        - restapinetwork
    ports:
        - 5000:5000
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONNECTION_STRING: "postgresql://admin:P@ssw0rd123@db:5432/graphqldb"
    depends_on:
      - db
  db:
    image: postgres
    networks:
        - restapinetwork
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_DB: graphqldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd123
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
networks: 
  restapinetwork:
    driver: "bridge"